### ISSUE TITLE
Add support for ios 16.4 rootless palera1n

### ISSUE THREAD

**Issue by iwannet** [akemin-dayo/AppSync#164] opened 2023-05-20 15:07 UTC
Could you please add support for ios 16.4 rootless palera1n cuz now i need to use trollstore but appsync unified is much better, Thanks.

**Comment by akemin-dayo** [comment] 2023-05-21 03:02
Duplicate of https://github.com/akemin-dayo/AppSync/issues/155.

Full support for "rootless" mode jailbreaks will be coming within the next week or so. Apologies for the wait.

**Closed by akemin-dayo** 2023-05-21 03:02 UTC

**Comment by iwannet** [comment] 2023-05-21 06:59
Thank you very much
