### ISSUE TITLE
Repo Update For Sileo/Dopamine

### ISSUE THREAD

**Issue by JEmlay** [akemin-dayo/AppSync#170] opened 2023-06-30 17:52 UTC
When you eventually release rootless updates do you plan to maintain the "cydia" named repo?  As is, it needs to be updated for Sileo/Dopamine.

Could not find release file for https://cydia.akemi.ai

This is needed for rootless targets.  Although, you'll need a rootless target first I suspect.

**Comment by akemin-dayo** [comment] 2023-06-30 17:56
The repo's subdomain will rename `cydia.akemi.ai` as it's just a name.

It will work with Cydia, Zebra, Sileo, and even just plain CLI APT.

As for rootless support, that would be a duplicate of #155.

**Closed by akemin-dayo** 2023-06-30 17:56 UTC

**Comment by JEmlay** [comment] 2023-06-30 18:13
I don't think you understood.  That's not a duplicate of #155.  The repo itself, right now, does not work with Sileo on Dopamine because that file/info is missing.  When using Sileo on Dopamine it's expecting that release file.  It has nothing to do with making apps work on rootless.

**Comment by JEmlay** [comment] 2023-06-30 19:44
This should be reopened until it's actually fixed.  As of right now it's pretty annoying to constantly get errors every single time I go into Sileo.  I would remove the repo but constantly watching Github is no more an inconvenience than getting the error. 

![IMG_E5983](https://github.com/akemin-dayo/AppSync/assets/1591895/0ffa17c7-607f-4cca-ac38-80ff63ea5e73)

**Comment by akemin-dayo** [comment] 2023-07-01 11:42
The repo itself currently does not support rootless targets because there are no rootless packages.

AppSync Unified and appinst will be the first two rootless packages going up on it shortly, which will resolve both #155 and this issue.
