### ISSUE TITLE
Failed to add repo on iOS 15.7.3 / iPhone 7 - Sileo Paler41n jailbreak

### ISSUE THREAD

**Issue by h4pp1n3ss** [akemin-dayo/AppSync#163] opened 2023-05-19 20:27 UTC
Hi,

I am trying to install AppSync Unified, but while adding akemi repo on Sileo package management, I received the following error.

Error: Didn't find architecture
DPKGArchitecture() in https://cydia.akemi.ai/ 
Release
Error: Could not find the release file for https://cydia.akemi.ai 

Any idea ? 

Regards,

**Comment by akemin-dayo** [comment] 2023-05-20 04:03
Duplicate of #155.

Full support for "rootless" mode jailbreaks will be coming within the next week or so. Apologies for the wait.

**Closed by akemin-dayo** 2023-05-20 04:03 UTC
