### ISSUE TITLE
Appsync dont work for dopamine jailbreak

### ISSUE THREAD

**Issue by bakirfatah99** [akemin-dayo/AppSync#175] opened 2023-07-11 22:27 UTC
Pls appsync support for dopamine

**Comment by bakirfatah99** [comment] 2023-07-11 22:28
I need it so badly appsync

**Comment by bakirfatah99** [comment] 2023-07-11 22:29
Dopamine jailbreak isn't it good?

**Comment by bakirfatah99** [comment] 2023-07-18 04:56
????????

**Comment by akemin-dayo** [comment] 2023-07-27 05:48
This is now a duplicate of #174. Please track that issue and move all discussion to it.

**Closed by akemin-dayo** 2023-07-27 05:48 UTC
